### ISSUE TITLE
Nested Licensing Support

### ISSUE THREAD

**Issue by erayaydin** [licensezero/licensezero.com#8]
I think its a bad idea but I want to share with this community.

I think, there should be extra license. For example, I'm developing `A` project with use `B` project. `A` project is open-source also `B` is. Someone pulled my project and said "I want to buy license of A". Then I think he should buy `B` when purchasing my project

- A: Open Source Free - Closed Source/Commercial 10$ (Also use B library)
- B: Open Source Free - Closed Source/Commercial 25$

Then, someone want to buy A its should show `nested` licenses for it and check licenses:

- **Person 1 (Doesnt bought B)** - Should pay 35$ (10$->OwnerOfProjectA, 25$->OwnerOfProjectB)
- **Person 2 (Already bought B)** - Should pay 10$->OwnerOfProjectA

Is it bad idea?

**Comment by erayaydin** [comment]
Maybe this way we can create scripts for `composer`, `npm` and maybe `bower for checking total license pay.

**Comment by kemitchell** [comment]
The `licensezero quote` and `licensezero buy` commands currently inventory _all_ dependencies of a project, _including_ subdependencies, and create a checkout process for any missing licenses.

If your project depends on A, A depends on B, and both A and B are licensed under Prosperity terms, you will need two licenses for commercial use: one for A and one for B. `licensezero quote` will quote the cost of a license for A, as well as a license for B. `licensezero buy` will open a checkout page for both a license for A and a license for B.

**Comment by erayaydin** [comment]
Oh sorry I didn't notice that, my mistake. Sorry for that. Thank you for answer :heart:
